export const ACCOUNT_LINES = [
    "5000 - Cost of Goods Sold",
    "6024 - Payroll Suspense",
    "6037 - Employee Benefits - Education Assistance",
    "6100 - Contract Labor",
    "6105 - Child Care Reimbursement",
    "6110 - Honorariums - Guest Speaker/Worship Artist/Other",
    "6120 - Legal/Accounting Fees",
    "6130 - Other Professional Services",
    "6135 - Background Checks",
    "6140 - Licenses",
    "6200 - Lodging",
    "6205 - Transportation",
    "6210 - Meals - Travel",
    "6215 - Meals with Staff/Elders",
    "6218 - Meals with Non-Staff",
    "6220 - Meals - Church Functions & Events",
    "6240 - Guest Lodging, Meals, Transportation",
    "6300 - Benevolence",
    "6305 - Mission Trip Expenses",
    "6310 - Mission Support - Organizations",
    "6315 - Mission Support - Individuals",
    "6316 - Foster & Adoption Support",
    "6317 - Mission Outreach",
    "6350 - Activity Expense",
    "6360 - Conference, Convention, Webinar & Seminar Fees",
    "6365 - Membership Dues/Fees--Orgs, Clubs",
    "6370 - Special Events",
    "6410 - Flowers and Gifts",
    "6411 - Prizes & Giveaways",
    "6415 - Volunteer Appreciation",
    "6500 - Utilities",
    "6505 - Security",
    "6510 - Telephone",
    "6515 - Internet",
    "6520 - Insurance",
    "6525 - Website",
    "6530 - Maint/Repair Building & Grounds",
    "6531 - Maint/Repair Building & Grounds Upgrades",
    "6535 - Maint/Repair Equipment",
    "6538 - Safety",
    "6540 - Rental Expense - Facilities",
    "6545 - Rental Expense - Equipment",
    "6550 - Rental Expense - Events",
    "6610 - Advertising Promotions & Social Media",
    "6620 - Postage",
    "6630 - Printing",
    "6635 - Wardrobe/Merch for Advertising and Promotion",
    "6640 - Training, development, study materials",
    "6650 - Curriculum, Teaching Supplies, Sermon Props",
    "6651 - Creative Resources, Songs/Tracks/Voice-overs",
    "6655 - Stage and Set Design",
    "6660 - Supplies - Other",
    "6661 - Supplies - Ministry & Missions",
    "6663 - Supplies - Audio/Visual/Tech",
    "6665 - Supplies - Facilities",
    "6670 - Office Supplies",
    "6690 - Bank Fees and Other Fees",
    "6710 - Interest Expense",
    "6800 - Non Capital Equipment",
    "6805 - Computer Software and Subscriptions",
    "6810 - Non Capital Furniture, Fixtures, Decorations",
    "6815 - Non Capital Signage and Banners",
    "7000 - Suspense"
]

export const DEPARTMENTS = [
    'ADM - Admin and Finance',
    'ADM HUM - Human Resources',
    'BEN - Missions - Compassion & Benevolence',
    'CHI - Children\'s Ministry',
    'CHI GEN - Children\'s Ministry - General',
    'CHI MDO - HRKS Highridge Kids School',
    'CHO MIN - Chosen Ministries',
    'CRE - Creative Arts',
    'CRE MIN - Ministry Development',
    'DAA - Depreciation & Amortization (Program)',
    'FAC - Facility Administration',
    'FAC MIN - Facilities Ministry',
    'FAM - Foster & Adoption Mission / Benevolence',
    'FIR - First Impressions',
    'FRE - Freedom',
    'GLO - Global',
    'GLO ETH - Ethiopia Mission Trip',
    'GLO MIS - Global Missions',
    'GLO TRP - Global Mission Trips',
    'GRP - Groups',
    'H4H - Heart for the House',
    'HRC - HRC Groups',
    'IT - Information Technology',
    'ITM - Information Technology Ministry',
    'KB H4H - Kingdom Builders & Heart for the House',
    'LOC MIS - Local Missions',
    'LSS - Legal and Support Services',
    'MAR - Marriage',
    'MED - Media',
    'MED COM - Content and Communications',
    'MED MIN - Media - Ministry',
    'MED SOC - Social Media',
    'MED VIS - Visual Media',
    'MEN - Men\'s Ministry',
    'MER - Merchandise',
    'MIS TRP - Mission Trips',
    'NAT - Missions - National',
    'NEX GEN - Next Generation',
    'PER ADM - Personnel Administration and Finance',
    'PER FAC - Personnel (Facilities)',
    'PER MED - Personnel Media',
    'PER MIN - Personnel Ministry',
    'PER MNS - Personnel Ministry Other',
    'PER SUP - Personnel Support Teams',
    'REL - Care',
    'SEN CAM - Campus Pastor',
    'SEN LP - Lead Pastor',
    'SEN XP - Executive Pastor',
    'SEN XTP - Executive Teaching Pastor',
    'SGT - Spiritual Growth Track',
    'STW - Stewardship',
    'SUS DPT - Suspense Dept',
    'TEC ART - Technical Arts',
    'TUE - Young Adults',
    'WOM - Women\'s Ministry',
    'WOR - Worship',
    'WOR CRE - Worship Creative Art',
    'WOR DEV - Development',
    'WOR MIN - Worship Ministry',
    'YOU - Youth',
]